# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(322, 491)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(0, 102, 75, 75))
        self.pushButton_clear.setStyleSheet("QPushButton{\n"
"background-color: rgb(63, 126, 0);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(63, 126, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_slash = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_slash.setGeometry(QtCore.QRect(160, 102, 75, 75))
        self.pushButton_slash.setStyleSheet("QPushButton{\n"
"background-color: rgb(38, 14, 158);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(38, 14, 158);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_slash.setObjectName("pushButton_slash")
        self.pushButton_multiplication = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_multiplication.setGeometry(QtCore.QRect(240, 102, 75, 75))
        self.pushButton_multiplication.setStyleSheet("QPushButton{\n"
"background-color: rgb(38, 14, 158);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(38, 14, 158);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_multiplication.setObjectName("pushButton_multiplication")
        self.pushButton_subtraction = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_subtraction.setGeometry(QtCore.QRect(240, 179, 75, 75))
        self.pushButton_subtraction.setStyleSheet("QPushButton{\n"
"background-color: rgb(38, 14, 158);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(38, 14, 158);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_subtraction.setObjectName("pushButton_subtraction")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 179, 75, 75))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background-color: rgb(20, 95, 127);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(20, 95, 127);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(80, 179, 75, 75))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background-color: rgb(20, 95, 127);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(20, 95, 127);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(160, 179, 75, 75))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"background-color: rgb(20, 95, 127);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(20, 95, 127);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_plus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plus.setGeometry(QtCore.QRect(240, 256, 75, 75))
        self.pushButton_plus.setStyleSheet("QPushButton{\n"
"background-color: rgb(38, 14, 158);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(38, 14, 158);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 333, 75, 75))
        self.pushButton_1.setStyleSheet("QPushButton{\n"
"background-color: rgb(20, 95, 127);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(20, 95, 127);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 333, 75, 75))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(20, 95, 127);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 256, 75, 75))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background-color: rgb(20, 95, 127);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(20, 95, 127);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 333, 75, 75))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(20, 95, 127);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(20, 95, 127);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 256, 75, 75))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-color: rgb(20, 95, 127);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(20, 95, 127);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_result = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_result.setGeometry(QtCore.QRect(240, 333, 75, 155))
        self.pushButton_result.setStyleSheet("QPushButton{\n"
"background-color: rgb(38, 14, 158);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(38, 14, 158);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_result.setObjectName("pushButton_result")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 256, 75, 75))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color: rgb(20, 95, 127);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(20, 95, 127);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(0, 410, 155, 75))
        self.pushButton_0.setStyleSheet("QPushButton{\n"
"background-color: rgb(20, 95, 127);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(20, 95, 127);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_dot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dot.setGeometry(QtCore.QRect(160, 410, 75, 75))
        self.pushButton_dot.setStyleSheet("QPushButton{\n"
"background-color: rgb(63, 126, 0);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(63, 126, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 311, 91))
        self.label.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.pushButton_clear_plasOrNegative = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear_plasOrNegative.setGeometry(QtCore.QRect(80, 102, 75, 75))
        self.pushButton_clear_plasOrNegative.setStyleSheet("QPushButton{\n"
"background-color: rgb(63, 126, 0);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(63, 126, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_clear_plasOrNegative.setObjectName("pushButton_clear_plasOrNegative")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("CALCULATOR", "CALCULATOR"))
        self.pushButton_clear.setText(_translate("MainWindow", "C"))
        self.pushButton_slash.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.pushButton_slash.setText(_translate("MainWindow", "/"))
        self.pushButton_multiplication.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.pushButton_multiplication.setText(_translate("MainWindow", "X"))
        self.pushButton_subtraction.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.pushButton_subtraction.setText(_translate("MainWindow", "-"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_plus.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.pushButton_plus.setText(_translate("MainWindow", "+"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_result.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.pushButton_result.setText(_translate("MainWindow", "="))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_dot.setText(_translate("MainWindow", "."))
        self.label.setText(_translate("MainWindow", "0"))
        self.pushButton_clear_plasOrNegative.setText(_translate("MainWindow", "+/-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
